# Generated by Django 4.0.3 on 2022-04-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='power',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
