# Generated by Django 4.0.3 on 2022-04-11 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstAPI', '0004_alter_car_fleet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fleet',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='firstAPI.fleet'),
        ),
    ]
