# Generated by Django 4.0.3 on 2022-04-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstAPI', '0007_car_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='engine_volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='year_of_production',
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
    ]
