# Generated by Django 4.0.3 on 2022-04-11 11:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstAPI', '0008_car_description_car_engine_volume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year_of_production',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
