# Generated by Django 4.0.3 on 2022-04-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstAPI', '0009_alter_car_year_of_production'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='signature_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
